[package]
name = "kex_infra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kex_domain = { path = "../kex_domain" }
etherparse = "0.15"
pnet = "0.35"
hex = "0.4.3"